[package]
name = "drv-stm32l4-sys-api"
version = "0.1.0"
edition = "2021"

[dependencies]
hubpack = "0.1.2"
serde = { version = "1.0.215", default-features = false, features = ["derive"] }
userlib.workspace = true

[build-dependencies]
hubris-build.workspace = true
